[package]
build = "build.rs"

name = "ex_00"
version = "0.1.0"
edition = "2024"

[dependencies]
slint = "1.12.1"
serde = { version = "1.0.0", features = ["derive"] }
serde_json = "1.0.0"

[build-dependencies]
slint-build = "1.12.1"
